# Generated by Django 4.2.11 on 2026-05-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_progressrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.family'),
        ),
    ]
