# Generated by Django 4.2.11 on 2026-05-16 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='file_type',
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('admission_form', 'Admission Form'), ('certificate', 'Certificate'), ('letter', 'Letter'), ('other', 'Other')], default='admission_form', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
