# Generated by Django 4.2.11 on 2026-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
