# Generated by Django 4.2.11 on 2026-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markrecord',
            name='obtained_marks',
        ),
        migrations.AddField(
            model_name='markrecord',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('exam', 'Exam'), ('assignment', 'Assignment'), ('quiz', 'Quiz')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='markrecord',
            name='marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='markrecord',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='markrecord',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
